WebOneApp/Models/Resturant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebOneApp.Models
{
    public class Resturant
    {
        public Resturant()
        {
            imgPath = "~/Content/user.png";
            meals = new Dictionary<string,List<Meal>>();
            categories = new List<string>();
            guid = Guid.NewGuid().ToString().Split('-').First();
        }

        [Required]
        public int id { get; set; }
        [Required]
        public string guid { get; set; }
        [Required]
        [Display(Name = "Name")]
        public string name { get; set; }
        [Required]
        [Display(Name = "Image")]
        public string imgPath { get; set; }
        [NotMapped]
        public HttpPostedFileBase imageUpload { get; set; }
        public Dictionary<string,List<Meal>> meals { get; set; }
        public List<string> categories { get; set; }
    }
}

WebOneApp/Controllers/API/ResturantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Cors;
using System.Web.Http.Description;
using WebOneApp.Models;

namespace WebOneApp.Controllers.API
{
    [EnableCors(origins: "*", headers: "*", methods: "*")]
    public class ResturantsController : ApiController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: api/Resturants
        public IQueryable<Resturant> GetResturants()
        {
            var res = db.Resturants;
            foreach (var item in res)
            {
                item.imgPath = Helper.appendDomain(item.imgPath);
            }
            return res;
        }

        // GET: api/Resturants/5
        [ResponseType(typeof(Resturant))]
        public object GetResturant(string code)
        {
            try
            {
                Resturant resturant = db.Resturants.ToList().First(x => x.guid == code);
                resturant.categories = Helper.SortMeals(db.Meals.Where(x => x.resturantId == resturant.id).ToList(), resturant.meals);
                resturant.imgPath = Helper.appendDomain(resturant.imgPath);
                if (resturant == null)
                {
                    return NotFound();
                }

                return Ok(resturant);
            }
            catch (Exception)
            {
                return new { Errors = "Could not find resturant" };
            }

        }

        // PUT: api/Resturants/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutResturant(int id, Resturant resturant)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != resturant.id)
            {
                return BadRequest();
            }

            db.Entry(resturant).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ResturantExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Resturants
        [ResponseType(typeof(Resturant))]
        public IHttpActionResult PostResturant(Resturant resturant)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Resturants.Add(resturant);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = resturant.id }, resturant);
        }


        //Move these to the Branch Controller
        [Route("api/Rating")]
        [HttpGet]
        public object AddRating(int userId, int userRating, int branchId, string comment)
        {
            var user = db.AppUsers.Find(userId);
            if (String.IsNullOrEmpty(user.MobileNumber))
            {
                user.MobileNumber = branchId.ToString();
            }
            else
            {
                user.MobileNumber = user.MobileNumber + "," + branchId;
            }
            var rating = new Rating() { userId = userId, rating = userRating, branchId = branchId, comment = comment };
            if (db.Ratings.ToList().Where(x => x.branchId == branchId && x.userId == userId).ToList().Count() == 0)
            {
                db.Ratings.Add(rating);
                db.SaveChanges();
                rating.username = db.AppUsers.Find(rating.userId).Name;
                return rating;
            }
            else
            {
                return new { Errors = "Could not add rating" };
            }
        }

        [Route("api/Categories")]
        [HttpGet]
        public Dictionary<string, List<Meal>> Categories()
        {
            var categories = new List<String>() { "breakfast", "beef", "salads", "sandwiches", "dessert" };
            var ret = new Dictionary<string, List<Meal>>();
            var meals = db.Meals.ToList();
            foreach (var meal in meals)
            {
                meal.imgPath = Helper.appendDomain(meal.imgPath);
            }
            foreach (var category in categories)
            {
                foreach (var meal in meals)
                {
                    if (meal.category.ToLower() == category)
                    {
                        if (!ret.ContainsKey(category))
                        {
                            var list = new List<Meal>();
                            ret.Add(category, list);
                        }
                        else
                        {
                            ret[category].Add(meal);
                        }
                    }
                }
            }
            return ret;
        }

        [Route("api/UserRatings")]
        [HttpGet]
        public List<int> AddRating(int userId)
        {
            var ratings = db.Ratings.ToList().Where(x => x.userId == userId).ToList();
            var retList = new List<int>();
            foreach (var item in ratings)
            {
                retList.Add(item.branchId);
            }
            return retList;
        }

        [Route("api/UserReservations")]
        [HttpGet]
        public List<Reservation> UserReservations(string email, int branchId)
        {
            var reservations = db.Reservations.ToList().Where(x => x.email == email && x.branchId == branchId && x.status != "Cancelled").ToList();
            var retList = new List<Reservation>();
            foreach (var item in reservations)
            {
                retList.Add(item);
            }
            return retList;
        }

        [Route("api/cancelReservation")]
        [HttpGet]
        public object cancelReservation(int resId)
        {
            try
            {
                var reservation = db.Reservations.First(x => x.id == resId);
                reservation.status = "Cancelled";
                db.SaveChanges();
                return reservation;
            }
            catch (Exception ex)
            {
                return new { Error = ex.Message };
            }

        }
        // DELETE: api/Resturants/5
        [ResponseType(typeof(Resturant))]
        public IHttpActionResult DeleteResturant(int id)
        {
            Resturant resturant = db.Resturants.Find(id);
            if (resturant == null)
            {
                return NotFound();
            }

            db.Resturants.Remove(resturant);
            db.SaveChanges();

            return Ok(resturant);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool ResturantExists(int id)
        {
            return db.Resturants.Count(e => e.id == id) > 0;
        }
    }
}

WebOneApp/Controllers/MVC/MealsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebOneApp.Models;

namespace WebOneApp.Controllers
{
    [HandleError]
    public class MealsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Meals
        public ActionResult Index()
        {
            ViewBag.resturantId = new SelectList(db.Resturants, "id", "name");
            var meals = db.Meals.ToList();
            
            return View(meals);
        }

        // GET: Meals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meal meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            return View(meal);
        }

        // GET: Meals/Create
        public ActionResult Create()
        {
            ViewBag.category = new SelectList(Helper.getCategoryNames(db.Categories.ToList()));
            ViewBag.resturantId = new SelectList(db.Resturants, "id", "name");
            return View();
        }

        // POST: Meals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,resturantId,name,price,description,category,startDate,endDate,imgPath")] Meal meal)
        {
            ViewBag.category = new SelectList(Helper.getCategoryNames(db.Categories.ToList()));
            ViewBag.resturantId = new SelectList(db.Resturants, "id", "name");
            if (ModelState.IsValid)
            {
                if (db.Branches.Where(x => x.name.Replace(" ", "").Trim().ToLower() ==
                        meal.name.Replace(" ", "").Trim().ToLower() && x.restId == meal.resturantId).Count() == 0) {
                    db.Meals.Add(meal);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else{
                    ViewBag.error = "meal already exists";
                }

            }

            return View(meal);
        }

        // GET: Meals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meal meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }

            ViewBag.category = new SelectList(Helper.getCategoryNames(db.Categories.ToList()), meal.category);
            ViewBag.resturantId = new SelectList(db.Resturants, "id", "name", meal.resturantId);

            return View(meal);
        }

        // POST: Meals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,resturantId,name,price,description,category,startDate,endDate,imgPath")] Meal meal)
        {
            ViewBag.category = new SelectList(Helper.getCategoryNames(db.Categories.ToList()));
            ViewBag.resturantId = new SelectList(db.Resturants, "id", "name");
            if (ModelState.IsValid)
            {
                string targetPath = Server.MapPath("~");
                var randString = Helper.RandomString(7);
                var path = targetPath + @"Content\imgs\" + randString + ".png";
                try
                {
                    Helper.downloadImage(path, meal.imgPath);
                    meal.imgPath = randString + ".png";
                    db.Entry(meal).State = EntityState.Modified;
                    db.SaveChanges();
                }
                catch (Exception)
                {
                    return View(meal);
                }
                
                return RedirectToAction("Details","Resturants", new { id = meal.resturantId});
            }
            return View(meal);
        }

        // GET: Meals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meal meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            return View(meal);
        }

        // POST: Meals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Meal meal = db.Meals.Find(id);
            db.Meals.Remove(meal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebOneApp/Views/Resturants/AddMeal.cshtml
@model WebOneApp.Models.Meal

@{
    ViewBag.Title = "AddMeal";
}

<h2>Add @ViewBag.resturant Meal</h2>
@if (ViewBag.error != null)
{
    <p style="color: red">@ViewBag.error</p>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.category, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imgPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imgPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imgPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div>
                <label class="control-label col-md-2">Special ?</label>
                <input id="Special" type="checkbox" value="true" name="Special" class="form-control" />
            </div>
        </div>

        <div id="specialDiv" style="display:none">
            <div class="form-group">
                @Html.LabelFor(model => model.startDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.startDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.startDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.endDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.endDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.endDate, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    $('#Special').click(function () {
        if ($(this).is(':checked')) {
            $("#specialDiv").show();
        } else {
            $("#specialDiv").hide();
        }
    });
</script>

WebOneApp/Views/Resturants/Create.cshtml
@model WebOneApp.Models.Resturant

@{
    ViewBag.Title = "Create";
}

<h4>Create</h4>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Resturant</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.imgPath, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.imgPath, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.imgPath, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebOneApp/Views/Resturants/Delete.cshtml
@model WebOneApp.Models.Resturant

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Resturant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            @Html.DisplayFor(model => model.guid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imgPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imgPath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebOneApp/Views/Resturants/Details.cshtml
@model WebOneApp.Models.Resturant

@{
    ViewBag.Title = "Details";
}

    <div style="background-image:url(@Model.imgPath);background-size: cover;background-position: center center;"  class="jumbotron jumbotron-fluid">
        <div style="height:150px;" class="container">
            <h1 style="color:black" class="display-4"></h1>
        </div>
    </div>
@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Add Meal", "AddMeal", new { resId = Model.id }) |
        @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    </p>
}
@{
    int counter = 0;
    var tabActive = "";
 }

    
<div class="row">
    <ul class="nav nav-tabs">
        @foreach (var meal in Model.meals)
        {
            if (counter == 0)
            {
                tabActive = "active";
            }
            else
            {
                tabActive = "";
            }
            <li class="@tabActive"><a data-toggle="tab" href="#@meal.Key.Replace(" ", String.Empty).Trim()">@meal.Key</a></li>
            counter++;
        }
    </ul>
    <div class="tab-content">
        @{
            counter = 0;
        }
        @foreach (var meal in Model.meals)
        {

            if (counter == 0)
            {
                tabActive = "active";
            }
            else
            {
                tabActive = "";
            }
            <div id="@meal.Key.Replace(" ", String.Empty).Trim()" class="tab-pane fade in @tabActive">
                @foreach (var item in meal.Value)
                {
                    <div class="col-sm-3">
                        <div class="card bg-light" style="width:100%;height:300PX;">
                            <img style="width: 150px;height: 150px" class="card-img-top" src=@item.imgPath alt="Card image">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-4">
                                        <h4>@item.name</h4>
                                    </div>
                                    <div class="col-md-4">
                                        <p>@item.price</p>
                                    </div>
                                </div>
                                <p class="text-wrap" style="word-wrap: break-word;">@item.description</p>

                                @if (User.IsInRole("Admin"))
                                {
                                    <div class="row">
                                        <div class="col-md-2">
                                            <a class="btn btn-primary" href="@Url.Action("EditMeal", new { id = item.id, restId = item.resturantId })">Edit</a>
                                        </div>
                                        <div class="col-md-2">
                                            <a class="btn btn-primary" href="@Url.Action("Delete", "Meals", new { id = item.id })">Delete</a>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
            counter++;
          }
        </div>
    </div>
    <br />
    <br />
    <br />
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            var panels = $('.accordion > dd').hide();
            $('.accordion > dt > a').click(function () {
                var $this = $(this);
                panels.slideUp();
                $this.parent().next().slideDown();
                return false;
            });
        });
    </script>

WebOneApp/Views/Resturants/Edit.cshtml
@model WebOneApp.Models.Resturant

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Resturant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imgPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imgPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imgPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebOneApp/Views/Resturants/EditMeal.cshtml
@model WebOneApp.Models.Meal

@{
    ViewBag.Title = "EditMeal";
}

<h2>Edit Meal</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Meal</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.category, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.startDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.startDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.startDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.endDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.endDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.endDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imgPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imgPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imgPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Details","Resturants",new { id = Model.resturantId})
</div>

WebOneApp/Views/Resturants/Index.cshtml
@model IEnumerable<WebOneApp.Models.Resturant>

@{
    ViewBag.Title = "Index";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

<div class="row">
    <br />
    <br />
    @foreach (var item in Model)
    {
        <div class="col-md-4">
            <div class="card" style="width:320px;height:300px;">
                <img style="width:250px;height:150px" class="card-img-top" src=@item.imgPath alt="Card image">
                <div class="card-body">
                    <h4>@item.name</h4>
                    <div class="row">
                        @if (User.IsInRole("Admin"))
                        {
                            <div class="col-md-2 btn btn-primary">
                                @Html.ActionLink("Edit", "Edit", new { id = item.id })
                            </div>
                            <div class="col-md-2 btn btn-primary">
                                @Html.ActionLink("Delete", "Delete", new { id = item.id })
                            </div>
                        }
                        <div class="col-md-3 btn btn-primary">
                            @Html.ActionLink("Details", "Details", new { id = item.id })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>